server.port=8086

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/staynomadly_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Mckinsey@8}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

app.jwt.secret=VGhpcy1Jcy1BLVZlcnktU2VjdXJlLUFuZC1NYXNzaXZlLUJhc2U2NC1TdHJpbmctRm9yLUpXVC1BdXRoZW50aWNhdGlvbi1IYXNoaW5nLVRoYXQtRXhjZWVkcy1BbGwtTWluaW11bS1IA==
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
